In [2]:
import pandas as pd
import numpy as np

# 1. Load the dataset
df = pd.read_csv(r"C:\Users\Sakshi Pawar\Downloads\Ecommerce_Transactions_Clean.csv")

# 2. Filter for successful transactions to measure true customer retention
df = df[df['Payment_Status'] == 'Success'].copy()

# 3. Convert Purchase_Date to datetime format
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])

df.head()

,Transaction_ID,Customer_ID,Purchase_Date,Product_Category,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Status,Acquisition_Channel,Customer_Segment,City,State,Gender,Age_Group
0,T000001,C0001,2025-11-13,Electronics,Monitor,3,2398,7194,Success,Organic Search,New,Mumbai,Maharashtra,Male,45-54
1,T000002,C0002,2025-08-16,Books,Novel,1,999,999,Success,Google Ads,New,Kolkata,West Bengal,Male,25-34
2,T000003,C0002,2025-09-30,Accessories,Wallet,3,2999,8997,Success,Google Ads,New,Kolkata,West Bengal,Male,25-34
3,T000004,C0003,2025-07-04,Beauty,Perfume,3,299,897,Success,Instagram,New,Chennai,Tamil Nadu,Male,25-34
4,T000005,C0004,2025-09-13,Electronics,Headphones,1,7498,7498,Success,Facebook Ads,VIP,Delhi,Delhi,Male,45-54

In [5]:
# Aggregate total revenue generated per cohort per month index
revenue_matrix = df.pivot_table(
    index='Cohort_Month', 
    columns='Cohort_Index', 
    values='Total_Amount', 
    aggfunc='sum'
)

print("--- COHORT REVENUE MATRIX ($) ---")
display(revenue_matrix.fillna(0).round(2))

--- COHORT REVENUE MATRIX ($) ---

Cohort_Index,0,1,2,3,4,5,6,7
Cohort_Month,,,,,,,,
2025-01,306660.0,153137.0,173286.0,62509.0,16930.0,2999.0,799.0,0.0
2025-02,384812.0,223599.0,91787.0,74624.0,18995.0,0.0,0.0,0.0
2025-03,370809.0,250746.0,174931.0,110492.0,77296.0,14481.0,0.0,0.0
2025-04,321128.0,211359.0,150896.0,56448.0,3995.0,5997.0,0.0,0.0
2025-05,238480.0,143710.0,81104.0,35047.0,32483.0,0.0,0.0,0.0
2025-06,342850.0,201720.0,172950.0,145436.0,110133.0,58239.0,1719.0,2874.0
2025-07,305602.0,163326.0,85625.0,121673.0,61653.0,20620.0,0.0,0.0
2025-08,413023.0,215305.0,135591.0,58351.0,23736.0,15796.0,0.0,0.0
2025-09,446726.0,297728.0,221571.0,70015.0,25660.0,34139.0,0.0,0.0
2025-10,348538.0,196876.0,97988.0,48856.0,998.0,9595.0,0.0,0.0
2025-11,320959.0,161324.0,71158.0,50417.0,46543.0,6590.0,0.0,0.0
2025-12,402725.0,133576.0,111633.0,52841.0,9704.0,0.0,0.0,0.0
2026-01,47673.0,11995.0,0.0,0.0,0.0,0.0,0.0,0.0