In [1]:
import pandas as pd

In [2]:
# Cross-tabulate geographic states with the acquisition channel
sales_data = pd.read_csv('Ecommerce_Transactions_Clean.csv')

state_channel = pd.crosstab(
    sales_data['State'],
    sales_data['Acquisition_Channel'],
    normalize='index'
) * 100

# Display formatted percentages
state_channel.round(2).astype(str) + '%'

Acquisition_Channel,Amazon,Email,Facebook Ads,Google Ads,Instagram,Organic Search,YouTube
State,,,,,,,
Delhi,16.09%,14.36%,10.89%,11.14%,17.82%,19.06%,10.64%
Karnataka,21.3%,8.64%,22.84%,8.02%,15.12%,17.9%,6.17%
Maharashtra,15.92%,12.31%,13.36%,17.57%,13.81%,12.16%,14.86%
Tamil Nadu,7.76%,10.45%,16.42%,17.01%,10.75%,14.03%,23.58%
Telangana,13.86%,15.35%,10.64%,18.07%,19.31%,13.12%,9.65%
West Bengal,14.32%,12.62%,13.11%,17.23%,9.22%,20.39%,13.11%

In [3]:
# Create cross-tabulation of Customer Segment and Product Category
sales_data = pd.read_csv('Ecommerce_Transactions_Clean.csv')


segment_category = pd.crosstab(
    sales_data['Customer_Segment'],
    sales_data['Product_Category'],
    normalize='index'
) * 100

# Display formatted percentages
segment_category.round(2).astype(str) + '%'

Product_Category,Accessories,Beauty,Books,Electronics,Fashion,Footwear,Grocery,Home & Kitchen,Sports,Toys
Customer_Segment,,,,,,,,,,
New,7.62%,11.28%,10.67%,8.54%,10.37%,9.76%,8.84%,9.6%,12.5%,10.82%
Premium,7.63%,10.09%,11.93%,10.33%,10.95%,10.46%,8.49%,11.32%,9.59%,9.23%
Returning,10.92%,11.03%,10.27%,8.43%,11.46%,10.16%,9.51%,10.38%,8.54%,9.3%
VIP,11.26%,9.93%,12.58%,11.92%,6.62%,12.58%,7.95%,9.93%,7.95%,9.27%